import { Preahvihear } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import SmoothScrolling from "./provider/SmoothScrolling";


const preahVihearFont = Preahvihear({
  weight: '400',
  subsets: ['latin'],
  variable: "--font-preah-vihear",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${preahVihearFont.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">

        <SmoothScrolling>
          <Navbar />
          {children}
          <Footer />
        </SmoothScrolling>

      </body>
    </html>
  );
}